export const FETCH_MENU = 'FETCH_MENU';
export const FETCH_SLIDER = 'FETCH_SLIDER';
export const FETCH_OUTSTADING = 'FETCH_OUTSTADING';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';